### ISSUE TITLE
RUn MultiTor on CentOS 8 error

### ISSUE THREAD

**Issue by phongtnit** [trimstray/multitor#34]
Hi,

I installed Tor Privoxy, HAProxy, NC, Polipo and HPTS on CentOS 8. After I run `multitor --init 20 --user root --socks-port 9000 --control-port 9900 --proxy privoxy --haproxy`

The output was:
```
socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false
    socks_port: 
        status: false

     Set processes: 20
           Created: 0
       Not created: 20
  Control password: *******

       Proxy state: running (haproxy » privoxy » socks)
```

I don't know why MultiTor cannot run, could you help me to fix the issue?

Another request, because I used Privoxy instead of Polipo, when I don't install Polipo and run MultiTor with the command `multitor --init 20 --user root --socks-port 9000 --control-port 9900 --proxy privoxy --haproxy` and the output was `not found in PATH: polipo`. So, I must install Polipo to run MultiTor. I guess it would be wonderful to fix this.

Many thanks,
